const actions = {
   STORE_CURRENT_USER: "STORE_CURRENT_USER",
   STORE_RECIPES: "STORE_RECIPES",
   STORE_INGREDIENT: "STORE_INGREDIENT",
   UPDATE_INDEX_OF_CURRENT_RECIPE: "UPDATE_INDEX_OF_CURRENT_RECIPE",
};

export default actions;
