const actions = {
   STORE_CURRENT_USER: "STORE_CURRENT_USER",
   STORE_ALL_RECIPES: "STORE_ALL_RECIPES",
   STORE_COOKED_RECIPE: "STORE_COOKED_RECIPE",
   STORE_EDITABLE_RECIPE: "STORE_EDITABLE_RECIPE",
   STORE_INGREDIENTS: "STORE_INGREDIENTS",
   STORE_OUT_OF_STOCK_INGREDIENT: "STORE_OUT_OF_STOCK_INGREDIENT",
   TOGGLE_INSTOCK_INGREDIENT: "TOGGLE_INSTOCK_INGREDIENT",
};

export default actions;
