const actions = {
   STORE_CURRENT_USER: "STORE_CURRENT_USER",
   STORE_ALL_RECIPES: "STORE_ALL_RECIPES",
   STORE_COOKED_RECIPE: "STORE_COOKED_RECIPE",
   STORE_EDITABLE_RECIPE: "STORE_EDITABLE_RECIPE",
};

export default actions;
