const recipeCard = [
   {
      recipeTitle: "Buffalo Chicken Wrap",
      prepTime: "5-10 mins",
      cookTime: "10-20 mins",
      servingSize: "2",
      mealFor: "dinner",
      ingredientAmount: "2",
      ingredient: "chicken thighs",
      stepsNum: "1",
      stepInstruction: "chop the chicken",
      noteSection: "make sure not to burn the TOAST!!",
   },
   {
      recipeTitle: "Cheese Pizza",
      prepTime: "5-10 mins",
      cookTime: "30 and up",
      servingSize: "4",
      mealFor: "Lunch",
      ingredientAmount: "2",
      ingredient: "chicken thighs",
      stepsNum: "1",
      stepInstruction: "chop the chicken",
      noteSection: "make sure not to burn the TOAST!!",
   },
   {
      recipeTitle: "Egg Burrito",
      prepTime: "5-10 mins",
      cookTime: "5-10 mins",
      servingSize: "1",
      mealFor: "breakfast",
      ingredientAmount: "2",
      ingredient: "chicken thighs",
      stepsNum: "1",
      stepInstruction: "chop the chicken",
      noteSection: "make sure not to burn the TOAST!!",
   },
   {
      recipeTitle: "French Toast",
      prepTime: "5-10 mins",
      cookTime: "10-20 mins",
      servingSize: "2",
      mealFor: "Brunch",
      ingredientAmount: "2",
      ingredient: "chicken thighs",
      stepsNum: "1",
      stepInstruction: "chop the chicken",
      noteSection: "make sure not to burn the TOAST!!",
   },
];
export default recipeCard;
