const recipeCard = [
   {
      recipeTitle: "Buffalo Chicken Wrap",
      cookTime: "10-20 mins",
      servingSize: "2",
      mealFor: "dinner",
      ingredientAmount: "5",
      ingredient: "chicken thighs",
      directions:
         "chop the chicken, toast the bread, stir the pot, melt the chesse, dont put too much milk.",
      favorites: false,
   },

   {
      recipeTitle: "shrimp pasta",
      cookTime: "10-20 mins",
      servingSize: "7",
      mealFor: "lunch",
      ingredientAmount: "5",
      ingredient: "chicken thighs",
      directions: "chop the chicken",
      favorites: false,
   },
   {
      recipeTitle: "Pizza",
      cookTime: "10-20 mins",
      servingSize: "8",
      mealFor: "breakfast",
      ingredientAmount: "2",
      ingredient: "chicken thighs",
      directions: "chop the chicken",
      favorites: false,
   },
   {
      recipeTitle: "Mexican Tacos",
      cookTime: "10-20 mins",
      servingSize: "4",
      mealFor: "brunch",
      ingredientAmount: "5",
      ingredient: "chicken thighs",
      directions: "chop the chicken",
      favorites: false,
   },
   {
      recipeTitle: "Mexican Tacos",
      cookTime: "10-20 mins",
      servingSize: "4",
      mealFor: "brunch",
      ingredientAmount: "5",
      ingredient: "chicken thighs",
      directions: "chop the chicken",
      favorites: false,
   },
   {
      recipeTitle: "Mexican Tacos",
      cookTime: "10-20 mins",
      servingSize: "4",
      mealFor: "brunch",
      ingredientAmount: "5",
      ingredient: "chicken thighs",
      directions: "chop the chicken",
      favorites: false,
   },
];
export default recipeCard;
